/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA3 (coord C4), SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SCL_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SCL_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SCL_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA4 (coord D4), SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDA_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDA_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDA_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB0 (coord E2), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA6 (coord E4), GATE1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GATE1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GATE1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GATE1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GATE1_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GATE1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GATE1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB13 (coord A2), GATE2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GATE2_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_GATE2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GATE2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GATE2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GATE2_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GATE2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTB5 (coord B2), DOWNLINK2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DOWNLINK2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DOWNLINK2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DOWNLINK2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA12 (coord A1), DOWNLINK1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DOWNLINK1_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DOWNLINK1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DOWNLINK1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
