/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MKL02Z32xxx4
package_id: MKL02Z32CAF4
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: C4, pin_signal: EXTAL0/PTA3/I2C0_SCL/I2C1_SDA, label: SCL, identifier: SCL}
- {pin_num: D4, pin_signal: XTAL0/PTA4/I2C0_SDA/I2C1_SCL, label: SDA, identifier: SDA}
- {pin_num: E2, pin_signal: ADC0_SE6/PTB0/IRQ_5/EXTRG_IN/SPI0_SCK, label: LED, identifier: LED}
- {pin_num: B2, pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b, label: DOWNLINK2, identifier: DOWNLINK2}
- {pin_num: E4, pin_signal: PTA6/TPM0_CH0/SPI0_MISO, label: GATE1, identifier: COIL1GATE;GATE1}
- {pin_num: A1, pin_signal: ADC0_SE0/CMP0_IN0/PTA12/IRQ_13/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0, label: DOWNLINK1, identifier: DOWNLINK1}
- {pin_num: D3, pin_signal: ADC0_SE5/CMP0_IN3/PTB1/IRQ_6/UART0_TX/UART0_RX, label: GND2, identifier: GND2}
- {pin_num: A2, pin_signal: ADC0_SE13/PTB13/TPM1_CH1, label: GATE2, identifier: GATE2}
- {pin_num: E3, pin_signal: PTA5/TPM0_CH1/SPI0_SS_b, label: GND1, identifier: GND1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C4, peripheral: I2C0, signal: SCL, pin_signal: EXTAL0/PTA3/I2C0_SCL/I2C1_SDA, pull_enable: enable}
  - {pin_num: D4, peripheral: I2C0, signal: SDA, pin_signal: XTAL0/PTA4/I2C0_SDA/I2C1_SCL, pull_enable: enable}
  - {pin_num: E2, peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE6/PTB0/IRQ_5/EXTRG_IN/SPI0_SCK, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: E4, peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/TPM0_CH0/SPI0_MISO, identifier: GATE1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: A2, peripheral: GPIOB, signal: 'GPIO, 13', pin_signal: ADC0_SE13/PTB13/TPM1_CH1, direction: OUTPUT}
  - {pin_num: B2, peripheral: CMP0, signal: 'IN, 1', pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b, pull_enable: disable}
  - {pin_num: A1, peripheral: CMP0, signal: 'IN, 0', pin_signal: ADC0_SE0/CMP0_IN0/PTA12/IRQ_13/LPTMR0_ALT2/TPM1_CH0/TPM_CLKIN0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    gpio_pin_config_t GATE1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin E4)  */
    GPIO_PinInit(BOARD_INITPINS_GATE1_GPIO, BOARD_INITPINS_GATE1_PIN, &GATE1_config);

    gpio_pin_config_t LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin E2)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GPIO, BOARD_INITPINS_LED_PIN, &LED_config);

    gpio_pin_config_t GATE2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB13 (pin A2)  */
    GPIO_PinInit(BOARD_INITPINS_GATE2_GPIO, BOARD_INITPINS_GATE2_PIN, &GATE2_config);

    /* PORTA12 (pin A1) is configured as CMP0_IN0 */
    PORT_SetPinMux(BOARD_INITPINS_DOWNLINK1_PORT, BOARD_INITPINS_DOWNLINK1_PIN, kPORT_PinDisabledOrAnalog);

    const port_pin_config_t SCL = {/* Internal pull-up resistor is enabled */
                                   kPORT_PullUp,
                                   /* Passive filter is disabled */
                                   kPORT_PassiveFilterDisable,
                                   /* Low drive strength is configured */
                                   kPORT_LowDriveStrength,
                                   /* Pin is configured as I2C0_SCL */
                                   kPORT_MuxAlt2};
    /* PORTA3 (pin C4) is configured as I2C0_SCL */
    PORT_SetPinConfig(BOARD_INITPINS_SCL_PORT, BOARD_INITPINS_SCL_PIN, &SCL);

    const port_pin_config_t SDA = {/* Internal pull-up resistor is enabled */
                                   kPORT_PullUp,
                                   /* Passive filter is disabled */
                                   kPORT_PassiveFilterDisable,
                                   /* Low drive strength is configured */
                                   kPORT_LowDriveStrength,
                                   /* Pin is configured as I2C0_SDA */
                                   kPORT_MuxAlt2};
    /* PORTA4 (pin D4) is configured as I2C0_SDA */
    PORT_SetPinConfig(BOARD_INITPINS_SDA_PORT, BOARD_INITPINS_SDA_PIN, &SDA);

    /* PORTA6 (pin E4) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_GATE1_PORT, BOARD_INITPINS_GATE1_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin E2) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_LED_PORT, BOARD_INITPINS_LED_PIN, kPORT_MuxAsGpio);

    /* PORTB13 (pin A2) is configured as PTB13 */
    PORT_SetPinMux(BOARD_INITPINS_GATE2_PORT, BOARD_INITPINS_GATE2_PIN, kPORT_MuxAsGpio);

    /* PORTB5 (pin B2) is configured as CMP0_IN1 */
    PORT_SetPinMux(BOARD_INITPINS_DOWNLINK2_PORT, BOARD_INITPINS_DOWNLINK2_PIN, kPORT_PinDisabledOrAnalog);

    PORTB->PCR[5] = ((PORTB->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
